module.exports = [
    {
        id: 42959,
        url: "https://yts.mx/movies/paul-doods-deadly-lunch-break-2021",
        imdb_code: "tt8137454",
        title: "Paul Dood's Deadly Lunch Break",
        title_english: "Paul Dood's Deadly Lunch Break",
        title_long: "Paul Dood's Deadly Lunch Break (2021)",
        slug: "paul-doods-deadly-lunch-break-2021",
        year: 2021,
        rating: 5.5,
        runtime: 95,
        genres: [
            "Action",
            "Comedy",
            "Thriller"
        ],
        summary: "A weedy charity-shop worker is set on winning the big national talent show. But when the actions of 5 selfish people cause him to miss his audition, he sets out to seek deathly revenge. It&#39;s 1 lunch break, 5 spectacular murders.",
        description_full: "A weedy charity-shop worker is set on winning the big national talent show. But when the actions of 5 selfish people cause him to miss his audition, he sets out to seek deathly revenge. It&#39;s 1 lunch break, 5 spectacular murders.",
        synopsis: "A weedy charity-shop worker is set on winning the big national talent show. But when the actions of 5 selfish people cause him to miss his audition, he sets out to seek deathly revenge. It&#39;s 1 lunch break, 5 spectacular murders.",
        yt_trailer_code: "PQZc-ma_bRQ",
        language: "en",
        mpa_rating: "",
        background_image: "https://yts.mx/assets/images/movies/paul_doods_deadly_lunch_break_2021/background.jpg",
        background_image_original: "https://yts.mx/assets/images/movies/paul_doods_deadly_lunch_break_2021/background.jpg",
        small_cover_image: "https://yts.mx/assets/images/movies/paul_doods_deadly_lunch_break_2021/small-cover.jpg",
        medium_cover_image: "https://yts.mx/assets/images/movies/paul_doods_deadly_lunch_break_2021/medium-cover.jpg",
        large_cover_image: "https://yts.mx/assets/images/movies/paul_doods_deadly_lunch_break_2021/large-cover.jpg",
        state: "ok",
        torrents: [
            {
                url: "https://yts.mx/torrent/download/99E22E1C95462F1BE670F35D0317F57E67296000",
                hash: "99E22E1C95462F1BE670F35D0317F57E67296000",
                quality: "720p",
                type: "web",
                seeds: 0,
                peers: 0,
                size: "874.52 MB",
                size_bytes: 917000684,
                date_uploaded: "2022-06-22 12:56:11",
                date_uploaded_unix: 1655895371
            },
            {
                url: "https://yts.mx/torrent/download/23D72CA59FB932A2442B8742B2EC8F3F1B11D250",
                hash: "23D72CA59FB932A2442B8742B2EC8F3F1B11D250",
                quality: "1080p",
                type: "web",
                seeds: 0,
                peers: 0,
                size: "1.75 GB",
                size_bytes: 1879048192,
                date_uploaded: "2022-06-22 13:53:10",
                date_uploaded_unix: 1655898790
            }
        ],
        date_uploaded: "2022-06-22 12:56:11",
        date_uploaded_unix: 1655895371
    },
    {
        id: 42958,
        url: "https://yts.mx/movies/love-gelato-2022",
        imdb_code: "tt15521050",
        title: "Love & Gelato",
        title_english: "Love & Gelato",
        title_long: "Love & Gelato (2022)",
        slug: "love-gelato-2022",
        year: 2022,
        rating: 0,
        runtime: 110,
        genres: [
            "Comedy",
            "Drama",
            "Romance"
        ],
        summary: "Lina is spending the summer in Tuscany, but she isn&#39;t in the mood for Italy&#39;s famous sunshine and fairy-tale landscape. She&#39;s only there because it was her mother&#39;s dying wish that she get to know her father. But what kind of father isn&#39;t around for sixteen years? All Lina wants to do is go back home. But then she is given a journal that her mom had kept when she lived in Italy. Suddenly Lina&#39;s uncovering a magical world of secret romances, art, and hidden bakeries. A world that inspires her, along with the ever-so-charming Ren, to follow in her mother&#39;s footsteps and unearth a secret that has been kept for far too long. It&#39;s a secret that will change everything she knew about her mother, her father and even herself.",
        description_full: "Lina is spending the summer in Tuscany, but she isn&#39;t in the mood for Italy&#39;s famous sunshine and fairy-tale landscape. She&#39;s only there because it was her mother&#39;s dying wish that she get to know her father. But what kind of father isn&#39;t around for sixteen years? All Lina wants to do is go back home. But then she is given a journal that her mom had kept when she lived in Italy. Suddenly Lina&#39;s uncovering a magical world of secret romances, art, and hidden bakeries. A world that inspires her, along with the ever-so-charming Ren, to follow in her mother&#39;s footsteps and unearth a secret that has been kept for far too long. It&#39;s a secret that will change everything she knew about her mother, her father and even herself.",
        synopsis: "Lina is spending the summer in Tuscany, but she isn&#39;t in the mood for Italy&#39;s famous sunshine and fairy-tale landscape. She&#39;s only there because it was her mother&#39;s dying wish that she get to know her father. But what kind of father isn&#39;t around for sixteen years? All Lina wants to do is go back home. But then she is given a journal that her mom had kept when she lived in Italy. Suddenly Lina&#39;s uncovering a magical world of secret romances, art, and hidden bakeries. A world that inspires her, along with the ever-so-charming Ren, to follow in her mother&#39;s footsteps and unearth a secret that has been kept for far too long. It&#39;s a secret that will change everything she knew about her mother, her father and even herself.",
        yt_trailer_code: "XIkQFUlBXF0",
        language: "en",
        mpa_rating: "",
        background_image: "https://yts.mx/assets/images/movies/love_gelato_2022/background.jpg",
        background_image_original: "https://yts.mx/assets/images/movies/love_gelato_2022/background.jpg",
        small_cover_image: "https://yts.mx/assets/images/movies/love_gelato_2022/small-cover.jpg",
        medium_cover_image: "https://yts.mx/assets/images/movies/love_gelato_2022/medium-cover.jpg",
        large_cover_image: "https://yts.mx/assets/images/movies/love_gelato_2022/large-cover.jpg",
        state: "ok",
        torrents: [
            {
                url: "https://yts.mx/torrent/download/E97A247F0FCC815B8F563C817C346CE879A4EF3D",
                hash: "E97A247F0FCC815B8F563C817C346CE879A4EF3D",
                quality: "720p",
                type: "web",
                seeds: 0,
                peers: 0,
                size: "1.01 GB",
                size_bytes: 1084479242,
                date_uploaded: "2022-06-22 10:56:56",
                date_uploaded_unix: 1655888216
            },
            {
                url: "https://yts.mx/torrent/download/2DDAA1E83378E3421600BD7D48446CF85C709BFC",
                hash: "2DDAA1E83378E3421600BD7D48446CF85C709BFC",
                quality: "1080p",
                type: "web",
                seeds: 165,
                peers: 80,
                size: "2.07 GB",
                size_bytes: 2222645576,
                date_uploaded: "2022-06-22 12:08:45",
                date_uploaded_unix: 1655892525
            }
        ],
        date_uploaded: "2022-06-22 10:56:56",
        date_uploaded_unix: 1655888216
    },
    {
        id: 42957,
        url: "https://yts.mx/movies/bruna-louise-demolition-2022",
        imdb_code: "tt20597270",
        title: "Bruna Louise: Demolition",
        title_english: "Bruna Louise: Demolition",
        title_long: "Bruna Louise: Demolition (2022)",
        slug: "bruna-louise-demolition-2022",
        year: 2022,
        rating: 0,
        runtime: 65,
        genres: [
            "Comedy",
            "Documentary"
        ],
        summary: "",
        description_full: "",
        synopsis: "",
        yt_trailer_code: "",
        language: "pt",
        mpa_rating: "",
        background_image: "https://yts.mx/assets/images/movies/bruna_louise_demolition_2022/background.jpg",
        background_image_original: "https://yts.mx/assets/images/movies/bruna_louise_demolition_2022/background.jpg",
        small_cover_image: "https://yts.mx/assets/images/movies/bruna_louise_demolition_2022/small-cover.jpg",
        medium_cover_image: "https://yts.mx/assets/images/movies/bruna_louise_demolition_2022/medium-cover.jpg",
        large_cover_image: "https://yts.mx/assets/images/movies/bruna_louise_demolition_2022/large-cover.jpg",
        state: "ok",
        torrents: [
            {
                url: "https://yts.mx/torrent/download/8FDC54895AB29023C360201B18165BD66F5A286E",
                hash: "8FDC54895AB29023C360201B18165BD66F5A286E",
                quality: "720p",
                type: "web",
                seeds: 12,
                peers: 8,
                size: "606.56 MB",
                size_bytes: 636024259,
                date_uploaded: "2022-06-22 09:35:54",
                date_uploaded_unix: 1655883354
            },
            {
                url: "https://yts.mx/torrent/download/53F2661BFC2392594CBD2FAA2854378D3D442D7A",
                hash: "53F2661BFC2392594CBD2FAA2854378D3D442D7A",
                quality: "1080p",
                type: "web",
                seeds: 22,
                peers: 13,
                size: "1.22 GB",
                size_bytes: 1309965025,
                date_uploaded: "2022-06-22 10:18:10",
                date_uploaded_unix: 1655885890
            }
        ],
        date_uploaded: "2022-06-22 09:35:54",
        date_uploaded_unix: 1655883354
    },
    {
        id: 42956,
        url: "https://yts.mx/movies/let-me-die-a-woman-1977",
        imdb_code: "tt0077848",
        title: "Let Me Die a Woman",
        title_english: "Let Me Die a Woman",
        title_long: "Let Me Die a Woman (1977)",
        slug: "let-me-die-a-woman-1977",
        year: 1977,
        rating: 5.2,
        runtime: 79,
        genres: [
            "Documentary"
        ],
        summary: "A documentary on the work of sex-change specialist Dr. Leo Wollman, including interviews with Dr. Wollman and a few of his patients, with an illustrated lecture on the various aspects of trans-identity plus actual footage of a gender reassignment operation, which is what gives the film its notoriety.",
        description_full: "A documentary on the work of sex-change specialist Dr. Leo Wollman, including interviews with Dr. Wollman and a few of his patients, with an illustrated lecture on the various aspects of trans-identity plus actual footage of a gender reassignment operation, which is what gives the film its notoriety.",
        synopsis: "A documentary on the work of sex-change specialist Dr. Leo Wollman, including interviews with Dr. Wollman and a few of his patients, with an illustrated lecture on the various aspects of trans-identity plus actual footage of a gender reassignment operation, which is what gives the film its notoriety.",
        yt_trailer_code: "",
        language: "en",
        mpa_rating: "",
        background_image: "https://yts.mx/assets/images/movies/let_me_die_a_woman_1977/background.jpg",
        background_image_original: "https://yts.mx/assets/images/movies/let_me_die_a_woman_1977/background.jpg",
        small_cover_image: "https://yts.mx/assets/images/movies/let_me_die_a_woman_1977/small-cover.jpg",
        medium_cover_image: "https://yts.mx/assets/images/movies/let_me_die_a_woman_1977/medium-cover.jpg",
        large_cover_image: "https://yts.mx/assets/images/movies/let_me_die_a_woman_1977/large-cover.jpg",
        state: "ok",
        torrents: [
            {
                url: "https://yts.mx/torrent/download/3C95E7F7BEB8CF311633FFEDB2776218CE595FE8",
                hash: "3C95E7F7BEB8CF311633FFEDB2776218CE595FE8",
                quality: "720p",
                type: "bluray",
                seeds: 99,
                peers: 37,
                size: "719.06 MB",
                size_bytes: 753989059,
                date_uploaded: "2022-06-22 09:08:47",
                date_uploaded_unix: 1655881727
            },
            {
                url: "https://yts.mx/torrent/download/5E8BE4B608A76033F46441A265B8A9181BC1054C",
                hash: "5E8BE4B608A76033F46441A265B8A9181BC1054C",
                quality: "1080p",
                type: "bluray",
                seeds: 115,
                peers: 72,
                size: "1.3 GB",
                size_bytes: 1395864371,
                date_uploaded: "2022-06-22 10:02:10",
                date_uploaded_unix: 1655884930
            }
        ],
        date_uploaded: "2022-06-22 09:08:47",
        date_uploaded_unix: 1655881727
    },
    {
        id: 42954,
        url: "https://yts.mx/movies/the-amazing-transplant-1970",
        imdb_code: "tt0065390",
        title: "The Amazing Transplant",
        title_english: "The Amazing Transplant",
        title_long: "The Amazing Transplant (1970)",
        slug: "the-amazing-transplant-1970",
        year: 1970,
        rating: 4,
        runtime: 77,
        genres: [
            "Fantasy",
            "Mystery"
        ],
        summary: "A seemingly pleasant fellow, Arthur goes berserk and rapes any woman in front of him wearing gold earrings. One woman tells the investigating detective (who is Arthur&#39;s uncle) she was raped, and flashes back to an erotic love making scene. Another one, a lesbian, relates a story that has to be seen to be believed. Other women flashback to their encounters with Arthur. We find out from a doctor, in another flashback, that Arthur underwent a penis transplant with a just-dead friend, unknowing his friend was a serial rapist who preyed on golden earring-ed women.",
        description_full: "A seemingly pleasant fellow, Arthur goes berserk and rapes any woman in front of him wearing gold earrings. One woman tells the investigating detective (who is Arthur&#39;s uncle) she was raped, and flashes back to an erotic love making scene. Another one, a lesbian, relates a story that has to be seen to be believed. Other women flashback to their encounters with Arthur. We find out from a doctor, in another flashback, that Arthur underwent a penis transplant with a just-dead friend, unknowing his friend was a serial rapist who preyed on golden earring-ed women.",
        synopsis: "A seemingly pleasant fellow, Arthur goes berserk and rapes any woman in front of him wearing gold earrings. One woman tells the investigating detective (who is Arthur&#39;s uncle) she was raped, and flashes back to an erotic love making scene. Another one, a lesbian, relates a story that has to be seen to be believed. Other women flashback to their encounters with Arthur. We find out from a doctor, in another flashback, that Arthur underwent a penis transplant with a just-dead friend, unknowing his friend was a serial rapist who preyed on golden earring-ed women.",
        yt_trailer_code: "",
        language: "en",
        mpa_rating: "",
        background_image: "https://yts.mx/assets/images/movies/the_amazing_transplant_1970/background.jpg",
        background_image_original: "https://yts.mx/assets/images/movies/the_amazing_transplant_1970/background.jpg",
        small_cover_image: "https://yts.mx/assets/images/movies/the_amazing_transplant_1970/small-cover.jpg",
        medium_cover_image: "https://yts.mx/assets/images/movies/the_amazing_transplant_1970/medium-cover.jpg",
        large_cover_image: "https://yts.mx/assets/images/movies/the_amazing_transplant_1970/large-cover.jpg",
        state: "ok",
        torrents: [
            {
                url: "https://yts.mx/torrent/download/AB4546CD49F19193F5DF58C098739400CF6171BA",
                hash: "AB4546CD49F19193F5DF58C098739400CF6171BA",
                quality: "720p",
                type: "bluray",
                seeds: 0,
                peers: 0,
                size: "657.33 MB",
                size_bytes: 689260462,
                date_uploaded: "2022-06-22 10:30:02",
                date_uploaded_unix: 1655886602
            },
            {
                url: "https://yts.mx/torrent/download/F7301F6A8B7044F893FB8438D6CE34AD961009BA",
                hash: "F7301F6A8B7044F893FB8438D6CE34AD961009BA",
                quality: "1080p",
                type: "bluray",
                seeds: 0,
                peers: 0,
                size: "1.19 GB",
                size_bytes: 1277752771,
                date_uploaded: "2022-06-22 11:20:56",
                date_uploaded_unix: 1655889656
            }
        ],
        date_uploaded: "2022-06-22 10:30:02",
        date_uploaded_unix: 1655886602
    },
    {
        id: 42955,
        url: "https://yts.mx/movies/the-spiral-road-1962",
        imdb_code: "tt0056516",
        title: "The Spiral Road",
        title_english: "The Spiral Road",
        title_long: "The Spiral Road (1962)",
        slug: "the-spiral-road-1962",
        year: 1962,
        rating: 6.1,
        runtime: 139,
        genres: [
            "Adventure",
            "Drama",
            "Romance"
        ],
        summary: "An arrogant young doctor helps an eccentric older doctor care for natives in the Dutch West Indies circa 1936. Challenged by love, leprosy and black magic, he undergoes a series of ordeals on a spiritual journey through the jungles of Java.",
        description_full: "An arrogant young doctor helps an eccentric older doctor care for natives in the Dutch West Indies circa 1936. Challenged by love, leprosy and black magic, he undergoes a series of ordeals on a spiritual journey through the jungles of Java.",
        synopsis: "An arrogant young doctor helps an eccentric older doctor care for natives in the Dutch West Indies circa 1936. Challenged by love, leprosy and black magic, he undergoes a series of ordeals on a spiritual journey through the jungles of Java.",
        yt_trailer_code: "",
        language: "en",
        mpa_rating: "",
        background_image: "https://yts.mx/assets/images/movies/the_spiral_road_1962/background.jpg",
        background_image_original: "https://yts.mx/assets/images/movies/the_spiral_road_1962/background.jpg",
        small_cover_image: "https://yts.mx/assets/images/movies/the_spiral_road_1962/small-cover.jpg",
        medium_cover_image: "https://yts.mx/assets/images/movies/the_spiral_road_1962/medium-cover.jpg",
        large_cover_image: "https://yts.mx/assets/images/movies/the_spiral_road_1962/large-cover.jpg",
        state: "ok",
        torrents: [
            {
                url: "https://yts.mx/torrent/download/98D555DB240805CB0FEE4B90D99EA833D3F3FD95",
                hash: "98D555DB240805CB0FEE4B90D99EA833D3F3FD95",
                quality: "720p",
                type: "bluray",
                seeds: 88,
                peers: 37,
                size: "1.25 GB",
                size_bytes: 1342177280,
                date_uploaded: "2022-06-22 09:55:45",
                date_uploaded_unix: 1655884545
            },
            {
                url: "https://yts.mx/torrent/download/92CB5EC02B753F080D5F03503B3B52257E215661",
                hash: "92CB5EC02B753F080D5F03503B3B52257E215661",
                quality: "1080p",
                type: "bluray",
                seeds: 102,
                peers: 53,
                size: "2.32 GB",
                size_bytes: 2491081032,
                date_uploaded: "2022-06-22 11:31:15",
                date_uploaded_unix: 1655890275
            }
        ],
        date_uploaded: "2022-06-22 09:55:45",
        date_uploaded_unix: 1655884545
    },
    {
        id: 42953,
        url: "https://m.media-amazon.com/images/M/MV5BMmIwZDMyYWUtNTU0ZS00ODJhLTg2ZmEtMTk5ZmYzODcxODYxXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg",
        imdb_code: "tt19849236",
        title: "Top-Gun : Maverick",
        title_english: "Jon Stewart: The Kennedy Center Mark Twain Prize for American Humor",
        title_long: "Jon Stewart: The Kennedy Center Mark Twain Prize for American Humor (2022)",
        slug: "jon-stewart-the-kennedy-center-mark-twain-prize-for-american-humor-2022",
        year: 2022,
        rating: 0,
        runtime: 120,
        genres: [
            "Action"
        ],
        summary: "",
        description_full: "",
        synopsis: "",
        yt_trailer_code: "",
        language: "en",
        mpa_rating: "",
        background_image: "https://yts.mx/assets/images/movies/jon_stewart_the_kennedy_center_mark_twain_prize_for_american_humor_2022/background.jpg",
        background_image_original: "https://yts.mx/assets/images/movies/jon_stewart_the_kennedy_center_mark_twain_prize_for_american_humor_2022/background.jpg",
        small_cover_image: "https://yts.mx/assets/images/movies/jon_stewart_the_kennedy_center_mark_twain_prize_for_american_humor_2022/small-cover.jpg",
        medium_cover_image: "https://m.media-amazon.com/images/M/MV5BMmIwZDMyYWUtNTU0ZS00ODJhLTg2ZmEtMTk5ZmYzODcxODYxXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg",
        large_cover_image: "https://m.media-amazon.com/images/M/MV5BMmIwZDMyYWUtNTU0ZS00ODJhLTg2ZmEtMTk5ZmYzODcxODYxXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg",
        state: "ok",
        torrents: [
            {
                url: "https://yts.mx/torrent/download/EE4F6BEB11205F4BAD19F33EA45D59987FCE4B3C",
                hash: "EE4F6BEB11205F4BAD19F33EA45D59987FCE4B3C",
                quality: "720p",
                type: "web",
                seeds: 0,
                peers: 0,
                size: "789.93 MB",
                size_bytes: 828301640,
                date_uploaded: "2022-06-22 08:42:18",
                date_uploaded_unix: 1655880138
            },
            {
                url: "https://yts.mx/torrent/download/B3F8797AC6BCD438E0207906A2CD0C7CE8E367F1",
                hash: "B3F8797AC6BCD438E0207906A2CD0C7CE8E367F1",
                quality: "1080p",
                type: "web",
                seeds: 0,
                peers: 0,
                size: "1.43 GB",
                size_bytes: 1535450808,
                date_uploaded: "2022-06-22 09:44:15",
                date_uploaded_unix: 1655883855
            }
        ],
        date_uploaded: "2022-06-22 08:42:18",
        date_uploaded_unix: 1655880138
    },
    {
        id: 42952,
        url: "https://yts.mx/movies/the-killer-meteors-1976",
        imdb_code: "tt0074747",
        title: "The Killer Meteors",
        title_english: "The Killer Meteors",
        title_long: "The Killer Meteors (1976)",
        slug: "the-killer-meteors-1976",
        year: 1976,
        rating: 4.8,
        runtime: 104,
        genres: [
            "Action",
            "Thriller"
        ],
        summary: "Mi Wey is a local hero named after &quot;Killer Meteors&quot;, his secret weapon which makes him invincible. However, when &quot;Immortal&quot; Wa Wu Bin, another powerful local character seeks his assistance, &quot;Killer meteor&quot; will face the greatest and the deadliest challenge of his life.",
        description_full: "Mi Wey is a local hero named after &quot;Killer Meteors&quot;, his secret weapon which makes him invincible. However, when &quot;Immortal&quot; Wa Wu Bin, another powerful local character seeks his assistance, &quot;Killer meteor&quot; will face the greatest and the deadliest challenge of his life.",
        synopsis: "Mi Wey is a local hero named after &quot;Killer Meteors&quot;, his secret weapon which makes him invincible. However, when &quot;Immortal&quot; Wa Wu Bin, another powerful local character seeks his assistance, &quot;Killer meteor&quot; will face the greatest and the deadliest challenge of his life.",
        yt_trailer_code: "C8sxbcxUBec",
        language: "zh",
        mpa_rating: "",
        background_image: "https://yts.mx/assets/images/movies/the_killer_meteors_1976/background.jpg",
        background_image_original: "https://yts.mx/assets/images/movies/the_killer_meteors_1976/background.jpg",
        small_cover_image: "https://yts.mx/assets/images/movies/the_killer_meteors_1976/small-cover.jpg",
        medium_cover_image: "https://yts.mx/assets/images/movies/the_killer_meteors_1976/medium-cover.jpg",
        large_cover_image: "https://yts.mx/assets/images/movies/the_killer_meteors_1976/large-cover.jpg",
        state: "ok",
        torrents: [
            {
                url: "https://yts.mx/torrent/download/FC7AA95B476280C089E0410AD69E0DFF853F561D",
                hash: "FC7AA95B476280C089E0410AD69E0DFF853F561D",
                quality: "720p",
                type: "bluray",
                seeds: 22,
                peers: 10,
                size: "961.55 MB",
                size_bytes: 1008258253,
                date_uploaded: "2022-06-21 23:07:36",
                date_uploaded_unix: 1655845656
            },
            {
                url: "https://yts.mx/torrent/download/FBCB9373804B99BFD2C5EED4E601F17799F4D433",
                hash: "FBCB9373804B99BFD2C5EED4E601F17799F4D433",
                quality: "1080p",
                type: "bluray",
                seeds: 34,
                peers: 12,
                size: "1.93 GB",
                size_bytes: 2072321720,
                date_uploaded: "2022-06-22 00:18:20",
                date_uploaded_unix: 1655849900
            }
        ],
        date_uploaded: "2022-06-21 23:07:36",
        date_uploaded_unix: 1655845656
    },
    {
        id: 42951,
        url: "https://yts.mx/movies/the-hard-man-1957",
        imdb_code: "tt0050485",
        title: "The Hard Man",
        title_english: "The Hard Man",
        title_long: "The Hard Man (1957)",
        slug: "the-hard-man-1957",
        year: 1957,
        rating: 6.1,
        runtime: 80,
        genres: [
            "Western"
        ],
        summary: "Steve Burden is a former lawman released for bringing in too many wanted men dead. The aging Sheriff of El Solito wants Steve for his Deputy and Steve takes the job knowing the last outlaw he killed was framed in El Solito. Looking for the man that framed him it appears that Rice Martin who controls El Solito is his man and Steve is quickly in trouble when Martin sends a man to kill him.",
        description_full: "Steve Burden is a former lawman released for bringing in too many wanted men dead. The aging Sheriff of El Solito wants Steve for his Deputy and Steve takes the job knowing the last outlaw he killed was framed in El Solito. Looking for the man that framed him it appears that Rice Martin who controls El Solito is his man and Steve is quickly in trouble when Martin sends a man to kill him.",
        synopsis: "Steve Burden is a former lawman released for bringing in too many wanted men dead. The aging Sheriff of El Solito wants Steve for his Deputy and Steve takes the job knowing the last outlaw he killed was framed in El Solito. Looking for the man that framed him it appears that Rice Martin who controls El Solito is his man and Steve is quickly in trouble when Martin sends a man to kill him.",
        yt_trailer_code: "",
        language: "en",
        mpa_rating: "",
        background_image: "https://yts.mx/assets/images/movies/the_hard_man_1957/background.jpg",
        background_image_original: "https://yts.mx/assets/images/movies/the_hard_man_1957/background.jpg",
        small_cover_image: "https://yts.mx/assets/images/movies/the_hard_man_1957/small-cover.jpg",
        medium_cover_image: "https://yts.mx/assets/images/movies/the_hard_man_1957/medium-cover.jpg",
        large_cover_image: "https://yts.mx/assets/images/movies/the_hard_man_1957/large-cover.jpg",
        state: "ok",
        torrents: [
            {
                url: "https://yts.mx/torrent/download/8E3BFCE78AEB5AFBC8CA3FFD9DDEB7DB4FB345B0",
                hash: "8E3BFCE78AEB5AFBC8CA3FFD9DDEB7DB4FB345B0",
                quality: "720p",
                type: "web",
                seeds: 73,
                peers: 22,
                size: "730.49 MB",
                size_bytes: 765974282,
                date_uploaded: "2022-06-21 19:04:02",
                date_uploaded_unix: 1655831042
            },
            {
                url: "https://yts.mx/torrent/download/74FBA1A93F5CC2D95DBAD17F8A04553AF02E9769",
                hash: "74FBA1A93F5CC2D95DBAD17F8A04553AF02E9769",
                quality: "1080p",
                type: "web",
                seeds: 84,
                peers: 32,
                size: "1.32 GB",
                size_bytes: 1417339208,
                date_uploaded: "2022-06-21 20:07:20",
                date_uploaded_unix: 1655834840
            }
        ],
        date_uploaded: "2022-06-21 19:04:02",
        date_uploaded_unix: 1655831042
    },
    {
        id: 42950,
        url: "https://yts.mx/movies/doctor-strange-in-the-multiverse-of-madness-2022",
        imdb_code: "tt9419884",
        title: "Doctor Strange in the Multiverse of Madness",
        title_english: "Doctor Strange in the Multiverse of Madness",
        title_long: "Doctor Strange in the Multiverse of Madness (2022)",
        slug: "doctor-strange-in-the-multiverse-of-madness-2022",
        year: 2022,
        rating: 7.3,
        runtime: 126,
        genres: [
            "Action",
            "Adventure",
            "Fantasy"
        ],
        summary: "Doctor Strange teams up with a mysterious teenage girl from his dreams who can travel across multiverses, to battle multiple threats, including other-universe versions of himself, which threaten to wipe out millions across the multiverse. They seek help from Wanda the Scarlet Witch, Wong and others.",
        description_full: "Doctor Strange teams up with a mysterious teenage girl from his dreams who can travel across multiverses, to battle multiple threats, including other-universe versions of himself, which threaten to wipe out millions across the multiverse. They seek help from Wanda the Scarlet Witch, Wong and others.",
        synopsis: "Doctor Strange teams up with a mysterious teenage girl from his dreams who can travel across multiverses, to battle multiple threats, including other-universe versions of himself, which threaten to wipe out millions across the multiverse. They seek help from Wanda the Scarlet Witch, Wong and others.",
        yt_trailer_code: "v-rHrkgVIsw",
        language: "en",
        mpa_rating: "PG-13",
        background_image: "https://yts.mx/assets/images/movies/doctor_strange_in_the_multiverse_of_madness_2022/background.jpg",
        background_image_original: "https://yts.mx/assets/images/movies/doctor_strange_in_the_multiverse_of_madness_2022/background.jpg",
        small_cover_image: "https://yts.mx/assets/images/movies/doctor_strange_in_the_multiverse_of_madness_2022/small-cover.jpg",
        medium_cover_image: "https://yts.mx/assets/images/movies/doctor_strange_in_the_multiverse_of_madness_2022/medium-cover.jpg",
        large_cover_image: "https://yts.mx/assets/images/movies/doctor_strange_in_the_multiverse_of_madness_2022/large-cover.jpg",
        state: "ok",
        torrents: [
            {
                url: "https://yts.mx/torrent/download/D4A7989B2AD3C95EFADABC1592F4F219E92E3986",
                hash: "D4A7989B2AD3C95EFADABC1592F4F219E92E3986",
                quality: "720p",
                type: "web",
                seeds: 9983,
                peers: 7284,
                size: "1.13 GB",
                size_bytes: 1213328261,
                date_uploaded: "2022-06-21 16:08:13",
                date_uploaded_unix: 1655820493
            },
            {
                url: "https://yts.mx/torrent/download/31F39E3AFE7C418EA6C10EA1B650E7D6D00680CF",
                hash: "31F39E3AFE7C418EA6C10EA1B650E7D6D00680CF",
                quality: "1080p",
                type: "web",
                seeds: 22442,
                peers: 10877,
                size: "2.33 GB",
                size_bytes: 2501818450,
                date_uploaded: "2022-06-21 17:24:30",
                date_uploaded_unix: 1655825070
            }
        ],
        date_uploaded: "2022-06-21 16:08:13",
        date_uploaded_unix: 1655820493
    },
    {
        id: 42949,
        url: "https://yts.mx/movies/callas-forever-2002",
        imdb_code: "tt0274407",
        title: "Callas Forever",
        title_english: "Callas Forever",
        title_long: "Callas Forever (2002)",
        slug: "callas-forever-2002",
        year: 2002,
        rating: 6.4,
        runtime: 108,
        genres: [
            "Biography",
            "Drama",
            "Music"
        ],
        summary: "In 1977, Maria Callas (Fanny Ardant), the most famous diva in the world, lives confined in her Paris apartment. Larry Kelly (Jeremy Irons), a producer friend, offers her to sing &quot;Carmen&quot; in a televised concert. Unfortunately, Maria&#39;s voice, tired and worn by years and strain, is not what it used to be. Larry knows the way around the problem: a technical stratagem will create the illusion. Maria, disregarding her friend Sarah Keller&#39;s (Dame Joan Plowright&#39;s) warning, agrees with the idea and the show is a tremendous success. With that in mind, Larry now considers a new version of &quot;Tosca&quot;. But this time, Maria objects to the subterfuge. Her decision will mark the beginning of the end for the legendary singer.",
        description_full: "In 1977, Maria Callas (Fanny Ardant), the most famous diva in the world, lives confined in her Paris apartment. Larry Kelly (Jeremy Irons), a producer friend, offers her to sing &quot;Carmen&quot; in a televised concert. Unfortunately, Maria&#39;s voice, tired and worn by years and strain, is not what it used to be. Larry knows the way around the problem: a technical stratagem will create the illusion. Maria, disregarding her friend Sarah Keller&#39;s (Dame Joan Plowright&#39;s) warning, agrees with the idea and the show is a tremendous success. With that in mind, Larry now considers a new version of &quot;Tosca&quot;. But this time, Maria objects to the subterfuge. Her decision will mark the beginning of the end for the legendary singer.",
        synopsis: "In 1977, Maria Callas (Fanny Ardant), the most famous diva in the world, lives confined in her Paris apartment. Larry Kelly (Jeremy Irons), a producer friend, offers her to sing &quot;Carmen&quot; in a televised concert. Unfortunately, Maria&#39;s voice, tired and worn by years and strain, is not what it used to be. Larry knows the way around the problem: a technical stratagem will create the illusion. Maria, disregarding her friend Sarah Keller&#39;s (Dame Joan Plowright&#39;s) warning, agrees with the idea and the show is a tremendous success. With that in mind, Larry now considers a new version of &quot;Tosca&quot;. But this time, Maria objects to the subterfuge. Her decision will mark the beginning of the end for the legendary singer.",
        yt_trailer_code: "",
        language: "en",
        mpa_rating: "PG-13",
        background_image: "https://yts.mx/assets/images/movies/callas_forever_2002/background.jpg",
        background_image_original: "https://yts.mx/assets/images/movies/callas_forever_2002/background.jpg",
        small_cover_image: "https://yts.mx/assets/images/movies/callas_forever_2002/small-cover.jpg",
        medium_cover_image: "https://yts.mx/assets/images/movies/callas_forever_2002/medium-cover.jpg",
        large_cover_image: "https://yts.mx/assets/images/movies/callas_forever_2002/large-cover.jpg",
        state: "ok",
        torrents: [
            {
                url: "https://yts.mx/torrent/download/5886BD3D6694E39AAF58A2998B4F955320986821",
                hash: "5886BD3D6694E39AAF58A2998B4F955320986821",
                quality: "720p",
                type: "bluray",
                seeds: 53,
                peers: 21,
                size: "999.69 MB",
                size_bytes: 1048250941,
                date_uploaded: "2022-06-21 19:01:31",
                date_uploaded_unix: 1655830891
            },
            {
                url: "https://yts.mx/torrent/download/0AB65E350A263DCD8E020CF73785EC48EDE63C9D",
                hash: "0AB65E350A263DCD8E020CF73785EC48EDE63C9D",
                quality: "1080p",
                type: "bluray",
                seeds: 78,
                peers: 31,
                size: "1.81 GB",
                size_bytes: 1943472701,
                date_uploaded: "2022-06-21 20:22:08",
                date_uploaded_unix: 1655835728
            }
        ],
        date_uploaded: "2022-06-21 19:01:31",
        date_uploaded_unix: 1655830891
    },
    {
        id: 42948,
        url: "https://yts.mx/movies/jack-o-1995",
        imdb_code: "tt0113449",
        title: "Jack-O",
        title_english: "Jack-O",
        title_long: "Jack-O (1995)",
        slug: "jack-o-1995",
        year: 1995,
        rating: 3.3,
        runtime: 88,
        genres: [
            "Horror"
        ],
        summary: "A long long time ago a wizard was put to death, but he swore vengeance on the townsfolk that did him in, particularly Arthur Kelly&#39;s family. Arthur had done the final graces on him when he came back to life as Mr. Jack the Pumpkin Man. The Kellys proliferated through the years, and when some devil-may-care teens accidentally unleash Jack-O, young Sean Kelly must stop him somehow as his suburban world is accosted and the attrition rate climbs.",
        description_full: "A long long time ago a wizard was put to death, but he swore vengeance on the townsfolk that did him in, particularly Arthur Kelly&#39;s family. Arthur had done the final graces on him when he came back to life as Mr. Jack the Pumpkin Man. The Kellys proliferated through the years, and when some devil-may-care teens accidentally unleash Jack-O, young Sean Kelly must stop him somehow as his suburban world is accosted and the attrition rate climbs.",
        synopsis: "A long long time ago a wizard was put to death, but he swore vengeance on the townsfolk that did him in, particularly Arthur Kelly&#39;s family. Arthur had done the final graces on him when he came back to life as Mr. Jack the Pumpkin Man. The Kellys proliferated through the years, and when some devil-may-care teens accidentally unleash Jack-O, young Sean Kelly must stop him somehow as his suburban world is accosted and the attrition rate climbs.",
        yt_trailer_code: "HKDijlJFSTk",
        language: "en",
        mpa_rating: "R",
        background_image: "https://yts.mx/assets/images/movies/jack_o_1995/background.jpg",
        background_image_original: "https://yts.mx/assets/images/movies/jack_o_1995/background.jpg",
        small_cover_image: "https://yts.mx/assets/images/movies/jack_o_1995/small-cover.jpg",
        medium_cover_image: "https://yts.mx/assets/images/movies/jack_o_1995/medium-cover.jpg",
        large_cover_image: "https://yts.mx/assets/images/movies/jack_o_1995/large-cover.jpg",
        state: "ok",
        torrents: [
            {
                url: "https://yts.mx/torrent/download/2534371F842CE8E629662D40BF74CB11C9BFE672",
                hash: "2534371F842CE8E629662D40BF74CB11C9BFE672",
                quality: "720p",
                type: "bluray",
                seeds: 59,
                peers: 20,
                size: "818.76 MB",
                size_bytes: 858532086,
                date_uploaded: "2022-06-21 17:19:05",
                date_uploaded_unix: 1655824745
            },
            {
                url: "https://yts.mx/torrent/download/4550F61B7E42E0D8AD68E39D1D4DA2E9F41D6D8C",
                hash: "4550F61B7E42E0D8AD68E39D1D4DA2E9F41D6D8C",
                quality: "1080p",
                type: "bluray",
                seeds: 74,
                peers: 15,
                size: "1.48 GB",
                size_bytes: 1589137900,
                date_uploaded: "2022-06-21 18:16:11",
                date_uploaded_unix: 1655828171
            }
        ],
        date_uploaded: "2022-06-21 17:19:05",
        date_uploaded_unix: 1655824745
    },
    {
        id: 42946,
        url: "https://yts.mx/movies/keyholes-are-for-peeping-1972",
        imdb_code: "tt0141506",
        title: "Keyholes Are for Peeping",
        title_english: "Keyholes Are for Peeping",
        title_long: "Keyholes Are for Peeping (1972)",
        slug: "keyholes-are-for-peeping-1972",
        year: 1972,
        rating: 4.6,
        runtime: 70,
        genres: [
            "Comedy"
        ],
        summary: "Funny parody of adult films starring Sammy Petrillo.",
        description_full: "Funny parody of adult films starring Sammy Petrillo.",
        synopsis: "Funny parody of adult films starring Sammy Petrillo.",
        yt_trailer_code: "",
        language: "en",
        mpa_rating: "",
        background_image: "https://yts.mx/assets/images/movies/keyholes_are_for_peeping_1972/background.jpg",
        background_image_original: "https://yts.mx/assets/images/movies/keyholes_are_for_peeping_1972/background.jpg",
        small_cover_image: "https://yts.mx/assets/images/movies/keyholes_are_for_peeping_1972/small-cover.jpg",
        medium_cover_image: "https://yts.mx/assets/images/movies/keyholes_are_for_peeping_1972/medium-cover.jpg",
        large_cover_image: "https://yts.mx/assets/images/movies/keyholes_are_for_peeping_1972/large-cover.jpg",
        state: "ok",
        torrents: [
            {
                url: "https://yts.mx/torrent/download/E5E8D0DB943240EFB686A625508892A710833645",
                hash: "E5E8D0DB943240EFB686A625508892A710833645",
                quality: "720p",
                type: "bluray",
                seeds: 180,
                peers: 89,
                size: "641.29 MB",
                size_bytes: 672441303,
                date_uploaded: "2022-06-21 15:53:57",
                date_uploaded_unix: 1655819637
            },
            {
                url: "https://yts.mx/torrent/download/672CA8B0BC8FB408EDD61528725EE9147E211937",
                hash: "672CA8B0BC8FB408EDD61528725EE9147E211937",
                quality: "1080p",
                type: "bluray",
                seeds: 195,
                peers: 76,
                size: "1.16 GB",
                size_bytes: 1245540516,
                date_uploaded: "2022-06-21 16:46:29",
                date_uploaded_unix: 1655822789
            }
        ],
        date_uploaded: "2022-06-21 15:53:57",
        date_uploaded_unix: 1655819637
    },
    {
        id: 42945,
        url: "https://yts.mx/movies/love-toy-1971",
        imdb_code: "tt0063244",
        title: "Love Toy",
        title_english: "Love Toy",
        title_long: "Love Toy (1971)",
        slug: "love-toy-1971",
        year: 1971,
        rating: 5.2,
        runtime: 75,
        genres: [
            "Thriller"
        ],
        summary: "Marcus loses all his belongings- his factory, house, car etc. to Alex at a game of Gin Rummy. Alex offers to drop all debts in return for one night with Marcus&#39; teenage daughter Chris. He agrees reluctantly but when he tries to intervene, Alex and his wife Mary bind him to a chair. She stays behind to keep an eye on him. Alex forces Chris to assume the roles of his childhood cat &#39;Samuel&#39; (she has to lap up milk from a bowl while nude), his mother (she has to nurse him), his wife, his child (he spanks her), his horse, and finally his mistress. Therewhile, Mary seems to be burning up in her green dress. She performs an erotic dance for Marcus, lapses into a memory of her mother having intercourse with a lover while she was a girl, and finally masturbates while watching Alex and Chris pretend they are lovers.",
        description_full: "Marcus loses all his belongings- his factory, house, car etc. to Alex at a game of Gin Rummy. Alex offers to drop all debts in return for one night with Marcus&#39; teenage daughter Chris. He agrees reluctantly but when he tries to intervene, Alex and his wife Mary bind him to a chair. She stays behind to keep an eye on him. Alex forces Chris to assume the roles of his childhood cat &#39;Samuel&#39; (she has to lap up milk from a bowl while nude), his mother (she has to nurse him), his wife, his child (he spanks her), his horse, and finally his mistress. Therewhile, Mary seems to be burning up in her green dress. She performs an erotic dance for Marcus, lapses into a memory of her mother having intercourse with a lover while she was a girl, and finally masturbates while watching Alex and Chris pretend they are lovers.",
        synopsis: "Marcus loses all his belongings- his factory, house, car etc. to Alex at a game of Gin Rummy. Alex offers to drop all debts in return for one night with Marcus&#39; teenage daughter Chris. He agrees reluctantly but when he tries to intervene, Alex and his wife Mary bind him to a chair. She stays behind to keep an eye on him. Alex forces Chris to assume the roles of his childhood cat &#39;Samuel&#39; (she has to lap up milk from a bowl while nude), his mother (she has to nurse him), his wife, his child (he spanks her), his horse, and finally his mistress. Therewhile, Mary seems to be burning up in her green dress. She performs an erotic dance for Marcus, lapses into a memory of her mother having intercourse with a lover while she was a girl, and finally masturbates while watching Alex and Chris pretend they are lovers.",
        yt_trailer_code: "",
        language: "en",
        mpa_rating: "",
        background_image: "https://yts.mx/assets/images/movies/love_toy_1971/background.jpg",
        background_image_original: "https://yts.mx/assets/images/movies/love_toy_1971/background.jpg",
        small_cover_image: "https://yts.mx/assets/images/movies/love_toy_1971/small-cover.jpg",
        medium_cover_image: "https://yts.mx/assets/images/movies/love_toy_1971/medium-cover.jpg",
        large_cover_image: "https://yts.mx/assets/images/movies/love_toy_1971/large-cover.jpg",
        state: "ok",
        torrents: [
            {
                url: "https://yts.mx/torrent/download/5043205522AACDEE89CF89D0271F9B2D4CF67C28",
                hash: "5043205522AACDEE89CF89D0271F9B2D4CF67C28",
                quality: "720p",
                type: "bluray",
                seeds: 397,
                peers: 150,
                size: "696.63 MB",
                size_bytes: 730469499,
                date_uploaded: "2022-06-21 16:02:27",
                date_uploaded_unix: 1655820147
            },
            {
                url: "https://yts.mx/torrent/download/CC3146D2F31DF3604881D5672B2A8416BC69571B",
                hash: "CC3146D2F31DF3604881D5672B2A8416BC69571B",
                quality: "1080p",
                type: "bluray",
                seeds: 385,
                peers: 129,
                size: "1.26 GB",
                size_bytes: 1352914698,
                date_uploaded: "2022-06-21 16:58:04",
                date_uploaded_unix: 1655823484
            }
        ],
        date_uploaded: "2022-06-21 16:02:27",
        date_uploaded_unix: 1655820147
    },
    {
        id: 42947,
        url: "https://yts.mx/movies/thriller-a-cruel-picture-1973",
        imdb_code: "tt0072285",
        title: "Thriller: A Cruel Picture",
        title_english: "Thriller: A Cruel Picture",
        title_long: "Thriller: A Cruel Picture (1973)",
        slug: "thriller-a-cruel-picture-1973",
        year: 1973,
        rating: 6.4,
        runtime: 104,
        genres: [
            "Crime",
            "Drama",
            "Thriller"
        ],
        summary: "Frigga lives with her parents on their farm. Unable to speak after being horrifically raped by an elderly man when she was young, her parents spend the majority of their money on speech therapy classes for their daughter in the hope that one day, she will speak again. One day, Frigga misses the bus to get to her speech therapy class. She accepts a ride off a suave looking gentlemen named Tony who pulls up beside her. Once they are in town, he takes her for a meal. Afterwards, he takes Frigga back to what appears to be his bachelor pad. He gives her wine that has probably been drugged, as she passes out after drinking it. The man then takes no time in bringing a crooked doctor in to get her fixed on high class heroin. After announcing to Frigga that she is now dependent on heroin and cannot last more than 48 hours without it, she must work as a prostitute for him. Frigga, obviously not thrilled by this news, attempts escape twice, but to no avail. On getting her very first client, she reacts by scratching down his face. Tony punishes her for this by removing an eye (the infamous supposed cadaver eye scene). Having found out that Tony sent a fake letter to her parents announcing in it that she hates her parents, Frigga makes her way home one Monday (her day off) only to discover that they have both apparently suicided from the lost of their only daughter. After this and the death of her friend and fellow prostitute Sally, Frigga seeks revenge on those who have wronged her, namely Tony and her clients. She spends her Mondays learning martial arts, buggy driving and shooting in order to suitably equip herself to take on the villians in her life. One of the blueprints as to why Tarantino&#39;s Kill Bill films exist, this film is an essential in the femme fatale revenge genre.",
        description_full: "Frigga lives with her parents on their farm. Unable to speak after being horrifically raped by an elderly man when she was young, her parents spend the majority of their money on speech therapy classes for their daughter in the hope that one day, she will speak again. One day, Frigga misses the bus to get to her speech therapy class. She accepts a ride off a suave looking gentlemen named Tony who pulls up beside her. Once they are in town, he takes her for a meal. Afterwards, he takes Frigga back to what appears to be his bachelor pad. He gives her wine that has probably been drugged, as she passes out after drinking it. The man then takes no time in bringing a crooked doctor in to get her fixed on high class heroin. After announcing to Frigga that she is now dependent on heroin and cannot last more than 48 hours without it, she must work as a prostitute for him. Frigga, obviously not thrilled by this news, attempts escape twice, but to no avail. On getting her very first client, she reacts by scratching down his face. Tony punishes her for this by removing an eye (the infamous supposed cadaver eye scene). Having found out that Tony sent a fake letter to her parents announcing in it that she hates her parents, Frigga makes her way home one Monday (her day off) only to discover that they have both apparently suicided from the lost of their only daughter. After this and the death of her friend and fellow prostitute Sally, Frigga seeks revenge on those who have wronged her, namely Tony and her clients. She spends her Mondays learning martial arts, buggy driving and shooting in order to suitably equip herself to take on the villians in her life. One of the blueprints as to why Tarantino&#39;s Kill Bill films exist, this film is an essential in the femme fatale revenge genre.",
        synopsis: "Frigga lives with her parents on their farm. Unable to speak after being horrifically raped by an elderly man when she was young, her parents spend the majority of their money on speech therapy classes for their daughter in the hope that one day, she will speak again. One day, Frigga misses the bus to get to her speech therapy class. She accepts a ride off a suave looking gentlemen named Tony who pulls up beside her. Once they are in town, he takes her for a meal. Afterwards, he takes Frigga back to what appears to be his bachelor pad. He gives her wine that has probably been drugged, as she passes out after drinking it. The man then takes no time in bringing a crooked doctor in to get her fixed on high class heroin. After announcing to Frigga that she is now dependent on heroin and cannot last more than 48 hours without it, she must work as a prostitute for him. Frigga, obviously not thrilled by this news, attempts escape twice, but to no avail. On getting her very first client, she reacts by scratching down his face. Tony punishes her for this by removing an eye (the infamous supposed cadaver eye scene). Having found out that Tony sent a fake letter to her parents announcing in it that she hates her parents, Frigga makes her way home one Monday (her day off) only to discover that they have both apparently suicided from the lost of their only daughter. After this and the death of her friend and fellow prostitute Sally, Frigga seeks revenge on those who have wronged her, namely Tony and her clients. She spends her Mondays learning martial arts, buggy driving and shooting in order to suitably equip herself to take on the villians in her life. One of the blueprints as to why Tarantino&#39;s Kill Bill films exist, this film is an essential in the femme fatale revenge genre.",
        yt_trailer_code: "VLoZqjxqZ4w",
        language: "sv",
        mpa_rating: "",
        background_image: "https://yts.mx/assets/images/movies/thriller_a_cruel_picture_1973/background.jpg",
        background_image_original: "https://yts.mx/assets/images/movies/thriller_a_cruel_picture_1973/background.jpg",
        small_cover_image: "https://yts.mx/assets/images/movies/thriller_a_cruel_picture_1973/small-cover.jpg",
        medium_cover_image: "https://yts.mx/assets/images/movies/thriller_a_cruel_picture_1973/medium-cover.jpg",
        large_cover_image: "https://yts.mx/assets/images/movies/thriller_a_cruel_picture_1973/large-cover.jpg",
        state: "ok",
        torrents: [
            {
                url: "https://yts.mx/torrent/download/4C9097BC0016A05CFAC9DC3C59618FBB87AFE284",
                hash: "4C9097BC0016A05CFAC9DC3C59618FBB87AFE284",
                quality: "720p",
                type: "bluray",
                seeds: 79,
                peers: 37,
                size: "995 MB",
                size_bytes: 1043333120,
                date_uploaded: "2022-06-21 17:03:27",
                date_uploaded_unix: 1655823807
            },
            {
                url: "https://yts.mx/torrent/download/BE754F20252276A7A06CF07F1B0D8A65D4454BC0",
                hash: "BE754F20252276A7A06CF07F1B0D8A65D4454BC0",
                quality: "1080p",
                type: "bluray",
                seeds: 103,
                peers: 53,
                size: "1.8 GB",
                size_bytes: 1932735283,
                date_uploaded: "2022-06-21 18:30:46",
                date_uploaded_unix: 1655829046
            }
        ],
        date_uploaded: "2022-06-21 17:03:27",
        date_uploaded_unix: 1655823807
    },
    {
        id: 42944,
        url: "https://yts.mx/movies/the-tiger-and-the-snow-2005",
        imdb_code: "tt0419198",
        title: "The Tiger and the Snow",
        title_english: "The Tiger and the Snow",
        title_long: "The Tiger and the Snow (2005)",
        slug: "the-tiger-and-the-snow-2005",
        year: 2005,
        rating: 7,
        runtime: 114,
        genres: [
            "Comedy",
            "Drama",
            "Romance"
        ],
        summary: "Love and injury in time of war. Attilio de Giovanni teaches poetry in Italy. He has a romantic soul, and women love him. But he is in love with Vittoria, and the love is unrequited. Every night he dreams of marrying her, in his boxer shorts and t-shirt, as Tom Waits sings. Vittoria travels to Iraq with her friend, Fuad, a poet; they are there with the second Gulf War breaks out. Vittoria is injured. Attilio must get to her side, and then, as war rages around him, he must find her the medical care she needs. In war, does love conquer all?",
        description_full: "Love and injury in time of war. Attilio de Giovanni teaches poetry in Italy. He has a romantic soul, and women love him. But he is in love with Vittoria, and the love is unrequited. Every night he dreams of marrying her, in his boxer shorts and t-shirt, as Tom Waits sings. Vittoria travels to Iraq with her friend, Fuad, a poet; they are there with the second Gulf War breaks out. Vittoria is injured. Attilio must get to her side, and then, as war rages around him, he must find her the medical care she needs. In war, does love conquer all?",
        synopsis: "Love and injury in time of war. Attilio de Giovanni teaches poetry in Italy. He has a romantic soul, and women love him. But he is in love with Vittoria, and the love is unrequited. Every night he dreams of marrying her, in his boxer shorts and t-shirt, as Tom Waits sings. Vittoria travels to Iraq with her friend, Fuad, a poet; they are there with the second Gulf War breaks out. Vittoria is injured. Attilio must get to her side, and then, as war rages around him, he must find her the medical care she needs. In war, does love conquer all?",
        yt_trailer_code: "Z50NSjFyFiA",
        language: "it",
        mpa_rating: "",
        background_image: "https://yts.mx/assets/images/movies/the_tiger_and_the_snow_2005/background.jpg",
        background_image_original: "https://yts.mx/assets/images/movies/the_tiger_and_the_snow_2005/background.jpg",
        small_cover_image: "https://yts.mx/assets/images/movies/the_tiger_and_the_snow_2005/small-cover.jpg",
        medium_cover_image: "https://yts.mx/assets/images/movies/the_tiger_and_the_snow_2005/medium-cover.jpg",
        large_cover_image: "https://yts.mx/assets/images/movies/the_tiger_and_the_snow_2005/large-cover.jpg",
        state: "ok",
        torrents: [
            {
                url: "https://yts.mx/torrent/download/AE92D721902F41CE0FF1497304A41868167043B7",
                hash: "AE92D721902F41CE0FF1497304A41868167043B7",
                quality: "720p",
                type: "bluray",
                seeds: 40,
                peers: 12,
                size: "1.04 GB",
                size_bytes: 1116691497,
                date_uploaded: "2022-06-21 12:53:27",
                date_uploaded_unix: 1655808807
            },
            {
                url: "https://yts.mx/torrent/download/F5178E6D66EF13ABA5E99582C4FA3769C105F68E",
                hash: "F5178E6D66EF13ABA5E99582C4FA3769C105F68E",
                quality: "1080p",
                type: "bluray",
                seeds: 48,
                peers: 26,
                size: "2.14 GB",
                size_bytes: 2297807503,
                date_uploaded: "2022-06-21 15:25:24",
                date_uploaded_unix: 1655817924
            }
        ],
        date_uploaded: "2022-06-21 12:53:27",
        date_uploaded_unix: 1655808807
    },
    {
        id: 42943,
        url: "https://yts.mx/movies/brandon-leake-a-family-affair-2022",
        imdb_code: "tt20358252",
        title: "Interseptor",
        title_english: "Brandon Leake: A Family Affair",
        title_long: "Brandon Leake: A Family Affair (2022)",
        slug: "brandon-leake-a-family-affair-2022",
        year: 2022,
        rating: 0,
        runtime: 0,
        genres: [
            "Documentary"
        ],
        summary: "Features eight original spoken word poems written and performed by &quot;America&#39;s Got Talent&quot; winner Brandon Leake. Viewers are going to get an intimate look at Brandon&#39;s life in Stockton, California.",
        description_full: "Features eight original spoken word poems written and performed by &quot;America&#39;s Got Talent&quot; winner Brandon Leake. Viewers are going to get an intimate look at Brandon&#39;s life in Stockton, California.",
        synopsis: "Features eight original spoken word poems written and performed by &quot;America&#39;s Got Talent&quot; winner Brandon Leake. Viewers are going to get an intimate look at Brandon&#39;s life in Stockton, California.",
        yt_trailer_code: "",
        language: "",
        mpa_rating: "",
        background_image: "https://yts.mx/assets/images/movies/brandon_leake_a_family_affair_2022/background.jpg",
        background_image_original: "https://yts.mx/assets/images/movies/brandon_leake_a_family_affair_2022/background.jpg",
        small_cover_image: "https://yts.mx/assets/images/movies/brandon_leake_a_family_affair_2022/small-cover.jpg",
        medium_cover_image: "https://assets-prd.ignimgs.com/2022/05/03/interceptor-en-us-main-vertical-1651614637898.jpg",
        large_cover_image: "https://assets-prd.ignimgs.com/2022/05/03/interceptor-en-us-main-vertical-1651614637898.jpg",
        state: "ok",
        torrents: [
            {
                url: "https://yts.mx/torrent/download/42A95028BC7D5B5D0048E6EF3FA26340B9578DEF",
                hash: "42A95028BC7D5B5D0048E6EF3FA26340B9578DEF",
                quality: "720p",
                type: "web",
                seeds: 13,
                peers: 5,
                size: "387.05 MB",
                size_bytes: 405851341,
                date_uploaded: "2022-06-21 11:53:53",
                date_uploaded_unix: 1655805233
            },
            {
                url: "https://yts.mx/torrent/download/473303AF29CBD22EF9457ACE57FF5FFA61AA8272",
                hash: "473303AF29CBD22EF9457ACE57FF5FFA61AA8272",
                quality: "1080p",
                type: "web",
                seeds: 15,
                peers: 8,
                size: "718.22 MB",
                size_bytes: 753108255,
                date_uploaded: "2022-06-21 12:21:56",
                date_uploaded_unix: 1655806916
            }
        ],
        date_uploaded: "2022-06-21 11:53:53",
        date_uploaded_unix: 1655805233
    },
    {
        id: 42942,
        url: "https://yts.mx/movies/the-black-pack-excellence-2022",
        imdb_code: "tt15790702",
        title: "The Black Pack: Excellence",
        title_english: "The Black Pack: Excellence",
        title_long: "The Black Pack: Excellence (2022)",
        slug: "the-black-pack-excellence-2022",
        year: 2022,
        rating: 0,
        runtime: 0,
        genres: [
            "Musical"
        ],
        summary: "Features special guests to commemorate Juneteenth and celebrate Black excellence and culture with musical and dance performances.",
        description_full: "Features special guests to commemorate Juneteenth and celebrate Black excellence and culture with musical and dance performances.",
        synopsis: "Features special guests to commemorate Juneteenth and celebrate Black excellence and culture with musical and dance performances.",
        yt_trailer_code: "",
        language: "en",
        mpa_rating: "",
        background_image: "https://yts.mx/assets/images/movies/the_black_pack_excellence_2022/background.jpg",
        background_image_original: "https://yts.mx/assets/images/movies/the_black_pack_excellence_2022/background.jpg",
        small_cover_image: "https://yts.mx/assets/images/movies/the_black_pack_excellence_2022/small-cover.jpg",
        medium_cover_image: "https://yts.mx/assets/images/movies/the_black_pack_excellence_2022/medium-cover.jpg",
        large_cover_image: "https://yts.mx/assets/images/movies/the_black_pack_excellence_2022/large-cover.jpg",
        state: "ok",
        torrents: [
            {
                url: "https://yts.mx/torrent/download/B3568FA2C74BC02A1C045535A457E0ACA1BE49CE",
                hash: "B3568FA2C74BC02A1C045535A457E0ACA1BE49CE",
                quality: "720p",
                type: "web",
                seeds: 18,
                peers: 7,
                size: "384.82 MB",
                size_bytes: 403513016,
                date_uploaded: "2022-06-21 11:48:03",
                date_uploaded_unix: 1655804883
            },
            {
                url: "https://yts.mx/torrent/download/6004A7205DDDE2D6F5BEF2F2AA524DC6DFA03802",
                hash: "6004A7205DDDE2D6F5BEF2F2AA524DC6DFA03802",
                quality: "1080p",
                type: "web",
                seeds: 31,
                peers: 13,
                size: "713.71 MB",
                size_bytes: 748379177,
                date_uploaded: "2022-06-21 12:17:52",
                date_uploaded_unix: 1655806672
            }
        ],
        date_uploaded: "2022-06-21 11:48:03",
        date_uploaded_unix: 1655804883
    },
    {
        id: 42941,
        url: "https://yts.mx/movies/the-house-in-between-2-2022",
        imdb_code: "tt18548702",
        title: "The House in Between 2",
        title_english: "The House in Between 2",
        title_long: "The House in Between 2 (2022)",
        slug: "the-house-in-between-2-2022",
        year: 2022,
        rating: 4.2,
        runtime: 102,
        genres: [
            "Documentary",
            "Horror",
            "Sci-Fi"
        ],
        summary: "Follow the most haunted house in the USA, and the fight of Alice and her paranormal work team so that she can return home. Who or what haunts Alice&#39;s house?",
        description_full: "Follow the most haunted house in the USA, and the fight of Alice and her paranormal work team so that she can return home. Who or what haunts Alice&#39;s house?",
        synopsis: "Follow the most haunted house in the USA, and the fight of Alice and her paranormal work team so that she can return home. Who or what haunts Alice&#39;s house?",
        yt_trailer_code: "olER70OUJa8",
        language: "en",
        mpa_rating: "",
        background_image: "https://yts.mx/assets/images/movies/the_house_in_between_2_2022/background.jpg",
        background_image_original: "https://yts.mx/assets/images/movies/the_house_in_between_2_2022/background.jpg",
        small_cover_image: "https://yts.mx/assets/images/movies/the_house_in_between_2_2022/small-cover.jpg",
        medium_cover_image: "https://yts.mx/assets/images/movies/the_house_in_between_2_2022/medium-cover.jpg",
        large_cover_image: "https://yts.mx/assets/images/movies/the_house_in_between_2_2022/large-cover.jpg",
        state: "ok",
        torrents: [
            {
                url: "https://yts.mx/torrent/download/621C2EAA1A667C503F3110E106A8DC038ED195CA",
                hash: "621C2EAA1A667C503F3110E106A8DC038ED195CA",
                quality: "720p",
                type: "web",
                seeds: 93,
                peers: 50,
                size: "939.84 MB",
                size_bytes: 985493668,
                date_uploaded: "2022-06-21 10:02:36",
                date_uploaded_unix: 1655798556
            },
            {
                url: "https://yts.mx/torrent/download/7640F7F08220AD7A1E91A6CAD78119B57D9B4FAD",
                hash: "7640F7F08220AD7A1E91A6CAD78119B57D9B4FAD",
                quality: "1080p",
                type: "web",
                seeds: 94,
                peers: 30,
                size: "1.89 GB",
                size_bytes: 2029372047,
                date_uploaded: "2022-06-21 11:13:43",
                date_uploaded_unix: 1655802823
            }
        ],
        date_uploaded: "2022-06-21 10:02:36",
        date_uploaded_unix: 1655798556
    },
    {
        id: 42940,
        url: "https://yts.mx/movies/joel-kim-booster-psychosexual-2022",
        imdb_code: "tt19869374",
        title: "Joel Kim Booster: Psychosexual",
        title_english: "Joel Kim Booster: Psychosexual",
        title_long: "Joel Kim Booster: Psychosexual (2022)",
        slug: "joel-kim-booster-psychosexual-2022",
        year: 2022,
        rating: 4.3,
        runtime: 67,
        genres: [
            "Comedy",
            "Documentary"
        ],
        summary: "Joel Kim Booster&#39;s first Netflix comedy special, talking about the cultural nuances of being Asian as he gets older and much more.",
        description_full: "Joel Kim Booster&#39;s first Netflix comedy special, talking about the cultural nuances of being Asian as he gets older and much more.",
        synopsis: "Joel Kim Booster&#39;s first Netflix comedy special, talking about the cultural nuances of being Asian as he gets older and much more.",
        yt_trailer_code: "-9hnR0EKApw",
        language: "en",
        mpa_rating: "",
        background_image: "https://yts.mx/assets/images/movies/joel_kim_booster_psychosexual_2022/background.jpg",
        background_image_original: "https://yts.mx/assets/images/movies/joel_kim_booster_psychosexual_2022/background.jpg",
        small_cover_image: "https://yts.mx/assets/images/movies/joel_kim_booster_psychosexual_2022/small-cover.jpg",
        medium_cover_image: "https://yts.mx/assets/images/movies/joel_kim_booster_psychosexual_2022/medium-cover.jpg",
        large_cover_image: "https://yts.mx/assets/images/movies/joel_kim_booster_psychosexual_2022/large-cover.jpg",
        state: "ok",
        torrents: [
            {
                url: "https://yts.mx/torrent/download/1A18339BBE72E44CDD38D4F58F3CEF1EB0C57D59",
                hash: "1A18339BBE72E44CDD38D4F58F3CEF1EB0C57D59",
                quality: "720p",
                type: "web",
                seeds: 53,
                peers: 25,
                size: "623.41 MB",
                size_bytes: 653692764,
                date_uploaded: "2022-06-21 15:18:41",
                date_uploaded_unix: 1655817521
            },
            {
                url: "https://yts.mx/torrent/download/1B2533F687779AC1BB1324CA1D38CEC6E06E13BC",
                hash: "1B2533F687779AC1BB1324CA1D38CEC6E06E13BC",
                quality: "1080p",
                type: "web",
                seeds: 57,
                peers: 24,
                size: "1.25 GB",
                size_bytes: 1342177280,
                date_uploaded: "2022-06-21 16:02:58",
                date_uploaded_unix: 1655820178
            }
        ],
        date_uploaded: "2022-06-21 15:18:41",
        date_uploaded_unix: 1655817521
    }
]